<!DOCTYPE html>
<html lang="fr">
<head>
        <meta charset="utf-8">
    <meta name="viewport" 
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    </title>Générateur de paragraphes</title>
</head>
<body>
    <h2>Generateur de paragraphes</h2>
<div>
    <label for="paragraphe">nb paragraphe</label>
    <input type="number"id="paragraphe" name="paragraphe" value="$paragraphe,>"min="1" max="30">
    <button type="submit" >Générer</button>
</div>
<?php
$array = array(
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ornare tellus posuere, pellentesque nulla venenatis, hendrerit mauris. Maecenas mattis ex nec ex faucibus dapibus. Suspendisse fringilla ipsum sit amet dapibus ultrices. Nam pulvinar, leo ac pretium pharetra, dui augue accumsan leo, at faucibus elit libero vel lectus. Nullam sapien lacus, euismod vitae rutrum vel, egestas at mauris. Aenean auctor luctus risus. Donec mauris nisi, ullamcorper quis dictum sed, pellentesque sit amet lorem. Praesent elementum enim sed ipsum scelerisque, nec dapibus justo aliquam. Mauris ornare dolor in massa porttitor, non facilisis urna bibendum. Sed id sagittis nulla. Vestibulum vehicula quam vestibulum, dapibus dolor ac, mollis lorem.

Nulla fermentum est eu tellus feugiat, at efficitur sapien consectetur. Curabitur sed dolor id orci auctor rutrum. Pellentesque mi orci, vulputate varius ultricies et, pretium quis libero. Ut eget dictum odio. Pellentesque gravida, diam ac malesuada convallis, justo eros tempus tortor, sed pretium lorem erat et eros. Proin aliquam semper elit, et sodales magna cursus ac. Aliquam erat volutpat. Sed porttitor erat id blandit lobortis. Suspendisse elementum mauris sed mi cursus mattis. Maecenas dapibus ornare ligula, nec maximus odio commodo egestas. Nam in maximus metus, et varius ex. Donec eget massa pretium nisl mattis euismod.

Sed sit amet luctus magna, non vehicula quam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi nulla elit, dapibus ac congue et, faucibus nec nunc. Nullam dictum bibendum dapibus. Sed quis tempor felis, venenatis mattis lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque efficitur ultricies lorem, non cursus augue porttitor sit amet.

Mauris ac tellus quis dui euismod efficitur in a ex. Morbi ac volutpat velit. Morbi vel vulputate leo, sit amet feugiat eros. Donec eu nisl iaculis sem varius auctor. Vestibulum condimentum posuere condimentum. Vestibulum at placerat neque. Mauris vel orci eu turpis elementum posuere. Fusce quis efficitur nunc. Donec fringilla pharetra augue, eleifend aliquam nunc elementum eget.

In eu consequat mauris, vestibulum sollicitudin ex. Pellentesque imperdiet lobortis mi a egestas. Etiam laoreet, urna ut ornare lacinia, arcu neque lacinia nunc, at hendrerit diam arcu non purus. Maecenas ac ligula eu metus convallis aliquam. Aenean elementum tincidunt sapien, in lobortis sapien tristique sit amet. Suspendisse est diam, condimentum et tincidunt quis, porttitor sodales sem. Sed in convallis erat. Sed at justo finibus, congue nulla ac, ultricies augue. Cras scelerisque odio commodo ligula vulputate, tincidunt tincidunt erat fringilla. Integer id odio a risus faucibus ornare non fermentum purus. Mauris et arcu elementum ex ultrices vehicula in vitae enim. Maecenas maximus elit at lectus rhoncus placerat.

Phasellus nibh erat, sagittis ut porta vel, gravida in ipsum. Etiam pellentesque odio in sollicitudin sollicitudin. Curabitur fermentum blandit nibh, eu varius dui viverra eu. In eu nulla consectetur, vehicula nulla ut, semper elit. Suspendisse vitae leo sed justo porta facilisis. Aliquam tortor dolor, mattis ut justo posuere, pellentesque hendrerit sapien. Ut quis congue nunc, sed vehicula diam. Etiam scelerisque vestibulum enim, in molestie arcu tincidunt at. Integer eget mattis odio, at commodo purus. Proin volutpat, purus sed molestie volutpat, lectus ipsum tempor ex, et tincidunt nunc nisl a urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ac condimentum arcu, sit amet tristique sapien. Maecenas sit amet nibh vitae eros porta luctus. Sed egestas nulla vel quam porta, egestas feugiat ipsum vestibulum.

Sed egestas viverra lorem vitae faucibus. Nulla quam sem, laoreet a tempor vitae, dignissim eu nisl. Phasellus sed odio sed nisi suscipit sagittis. Curabitur imperdiet orci in vulputate tristique. Curabitur tincidunt rhoncus euismod. Vestibulum at tempus libero. Fusce pellentesque lacinia eros vitae finibus. Duis mattis quam eget enim sodales rutrum. Cras non magna tellus. Proin faucibus, lectus at tristique sagittis, risus ante accumsan metus, quis venenatis ex tortor quis tellus. Donec venenatis a tellus nec mattis. Quisque rhoncus, turpis eu tincidunt pretium, nisi leo vehicula nisi, aliquam volutpat mi ex ut augue.

Curabitur pharetra quam sit amet justo suscipit scelerisque. Mauris id posuere lectus, eget scelerisque diam. Duis nisl magna, aliquam sed commodo ac, venenatis eu sapien. Nam ut leo elementum mi luctus iaculis. Duis tincidunt condimentum pretium. Proin vel sollicitudin magna, in fermentum nisl. Cras iaculis risus faucibus, sodales lorem vitae, accumsan odio. Aliquam nibh ante, vulputate non ex sed, facilisis ultricies augue. Quisque sollicitudin diam ut feugiat dapibus. Maecenas auctor ex sit amet orci blandit, non mollis ipsum congue. Sed tempor arcu lorem. Pellentesque ultrices diam efficitur tempor consequat.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus tempor ultrices ante. Donec consequat sed lorem et fringilla. In consequat lorem lorem, eget molestie nulla accumsan sed. Sed ultrices venenatis bibendum. Vivamus arcu felis, viverra a sagittis non, varius rutrum tortor. Nunc aliquet lectus et suscipit blandit.

Ut id sapien eget massa tristique hendrerit. Aliquam interdum porttitor magna et ultricies. Mauris sodales, odio eget lobortis consectetur, arcu elit molestie lorem, sit amet imperdiet nibh turpis vel nibh. Praesent rutrum dui bibendum efficitur sodales. Nullam ut ante nec ipsum vulputate tincidunt vel eget sem. In at orci at augue tincidunt tincidunt. Quisque leo arcu, rutrum vitae tempor vitae, eleifend nec lectus. Vestibulum a dolor eu lectus tristique tempor at sed orci. Nulla quis lectus hendrerit erat tempus scelerisque vitae eu nisi. Curabitur varius justo a ullamcorper facilisis. Curabitur non semper eros.

Vestibulum eget placerat ante. Pellentesque a convallis neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris interdum, elit sed placerat accumsan, arcu turpis mattis metus, sed pulvinar libero massa in nulla. Praesent consequat venenatis nulla at elementum. Morbi metus velit, feugiat id risus at, auctor dapibus orci. Sed vel finibus turpis, non bibendum est. Suspendisse aliquet, tellus sit amet sagittis tempor, nisi diam fringilla purus, eu euismod eros ante sit amet elit. Phasellus sed lorem in urna porttitor interdum.

Curabitur non lacus eget dolor tempus ultricies at at ex. Nunc feugiat mauris elit, at vulputate tortor tempor quis. Aenean lorem ipsum, rhoncus ac tortor ac, mattis maximus mauris. Cras at tincidunt velit. Phasellus non justo commodo, iaculis urna sit amet, mattis erat. Sed ac ipsum massa. Donec a orci eu felis lacinia condimentum. Etiam in magna in nisi vulputate elementum eu vel magna. Donec non finibus dolor. Proin sit amet est id nibh fringilla accumsan sed id velit. Donec volutpat elit nunc, a dignissim felis tempor accumsan.

Cras eget lectus risus. Nullam at vestibulum nisi, vel dictum sapien. Vivamus purus quam, vulputate elementum rutrum sed, dictum in augue. Aliquam ac tortor luctus, malesuada ante ut, pellentesque lectus. Fusce congue quis lorem non consequat. Pellentesque ornare nibh non purus suscipit, at sodales tortor pharetra. Donec feugiat, magna at commodo posuere, quam odio consequat orci, non laoreet metus diam sit amet ante. Etiam odio lacus, sagittis quis blandit vel, venenatis non turpis. Etiam vel elit urna. Maecenas interdum sem justo, non suscipit enim volutpat vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed rutrum tortor in vulputate sollicitudin. Nunc lobortis, ex id pharetra imperdiet, est urna hendrerit lacus, ut volutpat ligula mi non dolor. Aliquam lacinia aliquam mattis.

Cras lacus quam, imperdiet id suscipit non, suscipit ac erat. Nulla vel eleifend velit. Sed luctus, quam id aliquet euismod, sem mauris vestibulum dolor, sed consectetur lorem nibh in libero. Sed aliquam dignissim lorem id blandit. Sed quis venenatis diam. Aenean nec libero in massa accumsan pellentesque ut vel neque. Ut eget purus sed purus congue commodo eget in justo. Nullam imperdiet et lacus et eleifend. Sed nec eros justo.

Quisque eget risus eget orci varius ornare. Etiam rutrum sodales congue. In laoreet gravida vehicula. Sed et odio ultricies sem tempor varius. Donec aliquet mi ac ante sollicitudin, vitae tempus metus hendrerit. Fusce mollis nec ante id fermentum. Vivamus non rhoncus turpis, sit amet venenatis metus. Morbi malesuada lacus quis elit consequat, a pulvinar eros placerat. Suspendisse vitae dui arcu. Maecenas ultrices rhoncus mi, nec facilisis sem egestas in. Maecenas vel magna porttitor, vestibulum elit et, semper eros. Etiam iaculis tortor eget sem vehicula, non vulputate arcu congue. Curabitur non sapien non risus bibendum laoreet at sed tortor.

Donec imperdiet elit ut dapibus ornare. Sed ornare malesuada nisl ac laoreet. Curabitur sit amet quam mollis, mollis purus non, finibus mi. Aliquam lorem ipsum, ultricies quis porta eu, iaculis a ipsum. Morbi diam sem, tristique in fringilla faucibus, pellentesque vel velit. Suspendisse sed ex id quam eleifend placerat. Suspendisse rhoncus magna ut nunc semper imperdiet ac nec lorem. Pellentesque sit amet varius mauris. Cras dapibus justo non neque vehicula, facilisis porta nulla ultricies. Sed varius aliquam aliquet. Aliquam ac viverra augue, id tincidunt leo. Nullam consectetur lectus eget hendrerit viverra. Nulla facilisis nulla eget congue sagittis. Donec consequat ipsum viverra odio pharetra egestas. Curabitur maximus dictum sollicitudin. Quisque a orci congue, hendrerit elit in, volutpat odio.

Etiam venenatis facilisis lorem eu pharetra. Pellentesque vitae viverra massa. Suspendisse dignissim in augue vel vulputate. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse at arcu metus. Sed tincidunt ultricies purus vel eleifend. Mauris tempor nibh eu felis pretium facilisis. Cras non lorem non odio molestie semper vel et erat. In vestibulum molestie orci, a facilisis justo maximus eu. Nulla tellus tortor, malesuada in fermentum nec, condimentum id enim.

Mauris volutpat ornare est eget pretium. Fusce aliquam ullamcorper auctor. Nunc condimentum nunc id purus egestas, et fringilla eros iaculis. Integer tincidunt non eros quis pretium. Vivamus sodales nulla sit amet ligula rhoncus iaculis sit amet scelerisque ipsum. Maecenas nec dolor rutrum, sodales nulla eget, convallis ipsum. Sed augue nisl, pulvinar condimentum eros id, sollicitudin luctus velit. Vestibulum bibendum ornare massa, eu ultrices nibh aliquam eu. Nulla nec sem id mauris suscipit pellentesque fringilla sit amet augue. Nulla non est posuere, rutrum erat vel, rutrum ipsum. Pellentesque porta a eros finibus tincidunt. Suspendisse gravida luctus diam non imperdiet. Fusce ex erat, cursus id risus at, luctus ultrices velit.

Integer aliquam aliquet quam, a efficitur quam maximus a. Quisque non dolor faucibus turpis suscipit suscipit non sit amet metus. Phasellus vestibulum nisi non libero finibus dapibus. Maecenas consectetur mauris risus, non blandit mi egestas sed. Suspendisse vitae porta orci. Praesent eleifend sapien eget nulla sodales tincidunt. Nulla facilisi. Nulla et fringilla massa, in volutpat lectus. Duis nec lectus urna. Aenean sagittis luctus urna, ut interdum erat ultrices sit amet. Fusce at cursus erat, dapibus varius eros. Duis lobortis elementum tellus, at auctor nisi ornare sit amet.

Praesent lacinia, urna sed sodales posuere, quam arcu iaculis risus, vulputate sagittis neque magna quis nunc. Curabitur interdum dictum sapien. Donec sodales, quam in egestas congue, libero erat tincidunt ex, non dictum mauris purus sit amet felis. Fusce maximus venenatis nunc at lacinia. Donec egestas commodo turpis sit amet ultricies. Nulla nec lacus urna. Mauris congue eget arcu et congue. Maecenas ac dui venenatis, scelerisque nunc sed, feugiat erat. Donec ultricies, augue nec eleifend elementum, massa eros porttitor mi, id euismod mauris odio in lacus. Maecenas blandit ante dui, at accumsan nisi scelerisque quis. Aenean sed maximus turpis. Sed eu nisi dolor. Sed laoreet suscipit tristique. Donec volutpat libero velit, aliquam hendrerit diam tincidunt in. In mi justo, laoreet aliquet eros ut, molestie iaculis lacus.

Nulla leo quam, facilisis et quam eu, convallis pharetra nisi. Etiam vitae lorem nisi. Nullam ut ipsum lacus. Etiam accumsan tortor dui, eu tincidunt libero pulvinar nec. In eleifend turpis quis odio laoreet feugiat. Donec justo libero, pulvinar non diam imperdiet, dignissim aliquam dui. In iaculis imperdiet tempus. Pellentesque dignissim nisi nec posuere mollis. Etiam eget neque ac urna efficitur egestas. Mauris tristique convallis ipsum vulputate blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi rutrum lacus urna, a fringilla nunc porta a. Sed consectetur rhoncus mauris sed finibus. Aliquam fermentum, lacus commodo consequat fermentum, leo nisl laoreet tortor, vel tincidunt massa purus quis turpis. In eget elementum sem, ac fringilla ex.

Pellentesque elit tellus, malesuada sit amet sem sed, convallis tincidunt magna. Nullam in magna vitae leo fermentum ultricies vitae eu arcu. Donec nec mauris viverra, efficitur massa vel, dictum mauris. Suspendisse iaculis sollicitudin rhoncus. Ut hendrerit orci leo, non dapibus neque interdum vitae. Quisque ornare vel libero at facilisis. Vestibulum porttitor rhoncus gravida. Cras et mauris dignissim dui ullamcorper iaculis at eu dolor.

Proin consectetur quis velit vel accumsan. Integer mattis sem eget lectus venenatis pretium. Cras fermentum, elit vel finibus pulvinar, neque nibh ultrices est, at lacinia odio risus consectetur lacus. Phasellus mattis nisi vel condimentum posuere. Donec at feugiat nisl. Nunc eget urna id dui iaculis vestibulum. Integer tempus tincidunt turpis, id interdum ipsum dapibus in. Nullam vel lobortis purus, ac pharetra eros. In rutrum odio ac nulla congue, tempus vestibulum justo mollis. Donec molestie leo non erat faucibus pulvinar.

Aliquam id mauris in dolor scelerisque ullamcorper mattis vitae justo. Donec scelerisque sit amet turpis nec gravida. Sed consequat turpis eget laoreet faucibus. Integer ac dui commodo, efficitur enim eget, iaculis ex. Nunc eleifend nibh eu diam consectetur varius. Donec posuere, metus a tincidunt dignissim, diam tortor ullamcorper mi, ut rutrum urna ipsum sit amet eros. Curabitur ligula lacus, aliquet ut velit ac, fermentum vehicula turpis. Sed nec faucibus nulla. Praesent molestie ornare diam, sed placerat nulla egestas vel. Donec at lectus urna.

Nam at fringilla odio. Pellentesque tempus ut est non efficitur. Sed efficitur velit risus, vitae sodales diam aliquam at. Vestibulum ut egestas magna. Donec vel convallis purus, non volutpat nisl. Pellentesque laoreet lacus sapien, ut mollis urna fermentum ac. In pretium elit id est euismod, a scelerisque ante pretium. Aenean porttitor vitae justo ac tristique. Vestibulum faucibus massa neque, vel blandit enim eleifend volutpat. Donec tempor tortor non egestas porta. Vivamus aliquet euismod pretium. Duis quis massa sit amet purus hendrerit dictum id ac tellus.

Mauris malesuada, enim et egestas ornare, eros magna egestas odio, ac elementum lorem massa ac orci. In efficitur viverra elit, ac varius nisl. Proin a sagittis lectus. Aenean laoreet elit at velit posuere, ut efficitur erat pellentesque. Ut ornare orci felis, eget hendrerit lacus volutpat suscipit. Praesent luctus magna vitae tempor ullamcorper. Vivamus facilisis purus ut porta porta. Curabitur luctus rutrum malesuada. Vestibulum tincidunt dui nec orci vehicula, ac dignissim elit placerat. Etiam nec bibendum mauris. Cras euismod, turpis nec semper commodo, mi eros gravida sem, vitae aliquet massa metus id turpis. Aliquam tempor dolor eget nisl dapibus, a pharetra orci blandit. Aliquam erat volutpat. Curabitur tempus, tortor ac sodales vulputate, enim lectus egestas justo, vitae molestie nibh est ac metus.

Proin nec nunc sodales, ultricies sem non, sodales erat. Nulla vitae augue ligula. Maecenas volutpat pellentesque imperdiet. Maecenas ut egestas tellus, et semper dolor. Etiam pellentesque mi tellus, vel vehicula diam rhoncus eget. Duis sed lectus et nisl dapibus aliquam. Phasellus sit amet neque consectetur, ornare ipsum convallis, varius diam. Nullam volutpat orci erat, ac aliquet tellus commodo cursus. Quisque risus arcu, pretium eu commodo vel, egestas vel libero. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas quis diam auctor, vehicula risus non, mattis urna. Cras eget aliquam risus, non tincidunt ligula. Praesent commodo diam id ante faucibus, eu faucibus eros pellentesque.

Sed sed pretium diam. Ut in luctus nibh, ac euismod metus. Sed blandit nunc et nisl dictum, hendrerit ultrices nisl porttitor. Nunc aliquam tortor nec velit vehicula, vitae varius magna facilisis. Integer ornare ullamcorper lorem, sit amet maximus nibh tincidunt vitae. Donec sagittis accumsan tortor, a pellentesque turpis. Etiam egestas auctor ex, vel hendrerit diam. In in mattis purus. Ut tincidunt enim fringilla egestas varius. Nam id bibendum nisl, non condimentum nisi. Cras dui libero, malesuada sit amet est eget, congue convallis quam.

Aliquam nec accumsan ante. Etiam efficitur scelerisque enim, sed placerat metus fermentum vel. Nam vestibulum nisi in arcu pellentesque ultricies. Nullam elementum ligula eu leo semper porttitor. Fusce fringilla quam id nibh commodo, vitae euismod eros tincidunt. Donec mollis, orci non tempus ullamcorper, erat eros cursus urna, ac suscipit nibh risus vel tortor. Curabitur felis metus, imperdiet interdum magna id, interdum finibus orci. Donec facilisis justo sed accumsan pellentesque. Fusce gravida dictum bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam aliquam nisl id nisl sodales finibus. Ut imperdiet porta diam, nec hendrerit massa suscipit vitae. Sed imperdiet, enim fringilla interdum dapibus, sapien nibh pharetra mauris, malesuada ornare lacus lectus eu sem. Duis at tincidunt leo. Curabitur tincidunt justo eget nisl feugiat gravida. Maecenas vel congue ipsum, vel faucibus nisi.

Maecenas non est ex. Curabitur at vulputate nisi. Quisque posuere, erat eget ultrices ullamcorper, arcu libero ullamcorper lorem, vestibulum pellentesque enim purus non eros. Maecenas bibendum ornare odio, ut congue eros ultricies malesuada. Vestibulum finibus tempus purus, sed commodo nunc cursus sed. Vivamus sed congue erat. Duis vitae mattis urna. Proin nec bibendum elit. Maecenas urna lorem, commodo et eleifend at, volutpat quis augue. Vivamus maximus cursus nibh, in eleifend felis. In ultricies aliquam lectus ac pellentesque. In est mauris, dapibus quis nibh vel, aliquam semper ex."
)?>
</body>
</html>